        !COMPILER-GENERATED INTERFACE MODULE: Sat May 17 01:01:28 2014
        MODULE EIMPS_ASPAR_B_SOURCES_LOCAL__genmod
          INTERFACE 
            SUBROUTINE EIMPS_ASPAR_B_SOURCES_LOCAL(IS,ID,ASPAR,B,U)
              USE DATAPOOL
              INTEGER(KIND=4), INTENT(IN) :: IS
              INTEGER(KIND=4), INTENT(IN) :: ID
              REAL(KIND=8), INTENT(INOUT) :: ASPAR(NNZ)
              REAL(KIND=8), INTENT(INOUT) :: B(MNP)
              REAL(KIND=8), INTENT(INOUT) :: U(MNP)
            END SUBROUTINE EIMPS_ASPAR_B_SOURCES_LOCAL
          END INTERFACE 
        END MODULE EIMPS_ASPAR_B_SOURCES_LOCAL__genmod
