    SUBROUTINE IMPLSCH_LOCAL (IPP, FL3, FL, IG, SL)

       USE DATAPOOL, ONLY : MNP, FR, WETAIL, FRTAIL, WP1TAIL, ISHALLO, FRINTF, COFRM4, CG, WK, &
     &                      DFIM, DFIMOFR, DFFR, DFFR2, WK, RKIND, EMEAN, FMEAN, TH, RKIND, DELU, &
     &                      JUMAX, DT4S, FRM5, IPHYS, LOUTWAM, CD, UFRIC, ALPHA_CH, Z0, ITEST, LCFLX,&
     &                      THWOLD, THWNEW, Z0OLD, Z0NEW, ROAIRO, ROAIRN, ZIDLOLD, ZIDLNEW, U10NEW, USNEW, &
     &                      U10OLD, FMEANWS, USOLD, TAUW, &
     &                      DELTH => DDIR, &
     &                      G => G9, &
     &                      ZPI => PI2, &
     &                      EPSMIN => SMALL, &
     &                      NANG => MDC, &
     &                      NFRE => MSC, &
     &                      INDEP => DEP, &
     &                      ROWATER => RHOW, &
     &                      RHOAIR => RHOA

      IMPLICIT NONE

      INTEGER, INTENT(IN) :: IPP

      INTEGER :: K,L,M,IG,ILEV,IDELT,IU06
      INTEGER :: MIJ
      INTEGER :: JU

      REAL(rkind) :: GTEMP1, GTEMP2, FLHAB, XJ, DELT, DELT5, XIMP, AKM1
      REAL(rkind) :: AK2VGM1, XN, PHIDIAG, TAU
      REAL(rkind) :: EMEANWS, USFM, GADIAG 
      REAL(rkind) :: F1MEAN, AKMEAN, XKMEAN
      REAL(rkind) :: PHIEPS, TAUOC, PHIAW, WSTAR
      REAL(rkind) :: TAUWLF,TAUWD,PHIAWDIAG,PHIAWUNR,PHIOC,PHIWA 

      INTEGER    , DIMENSION(NFRE)     :: FCONST
      REAL(rkind), DIMENSION(NANG)     :: SPRD
      REAL(rkind), DIMENSION(NFRE)     :: TEMP, TEMP2, DELFL
      REAL(rkind),DIMENSION(NANG,NFRE) :: SSDS,DSSDS,SSBF,DSSBF,SSNL4,DSSNL4,SSIN,DSSIN,FL,FL3,SL,CIWAB,XLLWS

      IDELT = INT(DT4S)
      SL = 0.d0
      FL = 0.d0

      CALL FKMEAN_LOCAL(IPP, FL3, EMEAN(IPP), FMEAN(IPP), &
     &            F1MEAN, AKMEAN, XKMEAN)

      IF (LOUTWAM) WRITE(111113,*) 'HS and TM'
      IF (LOUTWAM) WRITE(111113,'(10F15.7)') 4*SQRT(EMEAN(IPP)), FMEAN(IPP)

      IF (LOUTWAM) WRITE(111113,*) 'DIRECTIONAL PROPERTIES'
      DO K=1,NANG
        SPRD(K)=MAX(0.,COS(TH(K)-THWNEW(IPP)))**2
        WRITE(111113,'(I10,3G20.10)') K, SPRD(K), TH(K), THWNEW(IPP) 
      ENDDO

      XJ=U10NEW(IPP)/DELU
      JU=MIN(JUMAX, MAX(NINT(XJ),1))

      IF (LOUTWAM) WRITE(111113,*) 'SOME THINKS THAT DO NOT NEED TO BE ALWAYS RECOMPUTED'
      IF (LOUTWAM) WRITE(111113,*) U10NEW(IPP),DELU
      IF (LOUTWAM) WRITE(111113,*) JU,JUMAX,MAX(NINT(XJ),1)

      ILEV=1
      CALL AIRSEA_LOCAL (IPP, U10NEW(IPP), TAUW(IPP), USNEW(IPP), Z0NEW(IPP), &
     &   ILEV)

      IF (LOUTWAM) WRITE(111113,*) 'AFTER AIRSEA 1'
      IF (LOUTWAM) WRITE(111113,*) U10NEW(IPP), TAUW(IPP), &
      &                              USNEW(IPP), Z0NEW(IPP), ILEV

      IF(IPHYS.EQ.0) THEN
        CALL SINPUT_LOCAL (IPP, FL3, FL, THWNEW(IPP), USNEW(IPP), Z0NEW(IPP), &
     &             ROAIRN(IPP), ZIDLNEW(IPP), SL, XLLWS, SSIN, DSSIN)
      ELSE
        CALL SINPUT_ARD_LOCAL (IPP, FL3, FL, THWNEW(IPP), USNEW(IPP), Z0NEW(IPP), &
     &             ROAIRN(IPP), ZIDLNEW(IPP), SL, XLLWS, SSIN, DSSIN)
      ENDIF

      IF (LOUTWAM) WRITE(111113,*) 'AFTER SINPUT 1'
      IF (LOUTWAM) WRITE(111113,*) IPP, SUM(FL), SUM(SL)

      CALL FEMEANWS_LOCAL(IPP,FL3,EMEANWS,FMEANWS(IPP),XLLWS)
      CALL FRCUTINDEX_LOCAL(IPP, FMEAN(IPP), FMEANWS(IPP), MIJ)
      CALL STRESSO_LOCAL (IPP, FL3, THWNEW(IPP), USNEW(IPP), Z0NEW(IPP), &
     &              ROAIRN(IPP), TAUW(IPP), TAUWLF, PHIWA, &
     &              PHIAWDIAG, PHIAWUNR, SL, &
     &              MIJ, LCFLX)

      IF (LOUTWAM) WRITE(111113,*) 'AFTER STRESSO 1'
      IF (LOUTWAM) WRITE(111113,*) SUM(FL3), &

     &              THWNEW(IPP), USNEW(IPP), Z0NEW(IPP), &
     &              ROAIRN(IPP), TAUW(IPP), TAUWLF, PHIWA, &
     &              PHIAWDIAG, PHIAWUNR, SUM(SL), &
     &              MIJ

      CALL AIRSEA_LOCAL (IPP, U10NEW(IPP), TAUW(IPP), USNEW(IPP), Z0NEW(IPP), &
     &             ILEV)
      IF (LOUTWAM) WRITE(111113,*) 'AFTER AIRSEA 2'
      IF (LOUTWAM) WRITE(111113,*) U10NEW(IPP), TAUW(IPP), &
     &             USNEW(IPP), Z0NEW(IPP)

      CALL SNONLIN_LOCAL (IPP, FL3, FL, IG, SL, AKMEAN, SSNL4, DSSNL4)

      IF (LOUTWAM) WRITE(111113,*) 'AFTER SNON'
      IF (LOUTWAM) WRITE(111113,*) SUM(FL), SUM(SL)

      IF(IPHYS.EQ.0) THEN
        CALL SDISSIP_LOCAL (IPP, FL3 ,FL, IG, SL, F1MEAN, XKMEAN,&
     &                PHIOC, TAUWD, MIJ, SSDS, DSSDS)
      ELSE
        CALL SDISS_ARDH_VEC_LOCAL (IPP, FL3 ,FL, SL, F1MEAN, XKMEAN,&
     &                PHIOC, TAUWD, MIJ, SSDS, DSSDS)
      ENDIF

      IF (LOUTWAM) WRITE(111113,*) 'AFTER DISSIP' 
      IF (LOUTWAM) WRITE(111113,*) SUM(FL), SUM(SL) 
!SHALLOW
      !IF(ISHALLO.NE.1) CALL SBOTTOM (FL3, FL, IJS, IJL, IG, SL, SSBF, DSSBF)
!SHALLOW

!     Integration 
      IF (LOUTWAM) WRITE(111110,'(A20,3F20.10)') 'BEFORE INTEGRATION', SUM(FL), SUM(SL), SUM(FL3)

      DELT = IDELT
      XIMP = 1.0
      DELT5 = XIMP*DELT
      DO M=1,NFRE
        DELFL(M) = COFRM4(M)*DELT
      ENDDO
      USFM = USNEW(IPP)*MAX(FMEANWS(IPP),FMEAN(IPP))
      DO M=1,NFRE
        TEMP(M) = USFM*DELFL(M)
      ENDDO

      DO K=1,NANG
        DO M=1,NFRE
          GTEMP1 = MAX((1.-DELT5*FL(K,M)),1.)
          GTEMP2 = DELT*SL(K,M)/GTEMP1
          FLHAB = ABS(GTEMP2)
          FLHAB = MIN(FLHAB,TEMP(M))
          GTEMP1 = FL3(K,M)
          FL3(K,M) = FL3(K,M) + SIGN(FLHAB,GTEMP2) 
!AR: ICE            FLLOWEST = FLMINFR(JU(IJ),M)*SPRD(IJ,K)
!AR: ICE            FL3(IJ,K,M) = MAX(FL3(IJ,K,M),FLLOWEST)
!         WRITE(111110,'(7F20.10)') FL3(K,M),GTEMP1,FLHAB,TEMP(M),FL(K,M),SL(K,M)
        ENDDO
      ENDDO
!     End of Integration 

      IF (LOUTWAM) WRITE(111110,'(A20,3F20.10)') 'AFTER INTEGRATION', SUM(FL), SUM(SL), SUM(FL3)

!     Merge Tail ...
      CALL FKMEAN_LOCAL(IPP, FL3, EMEAN(IPP), FMEAN(IPP), F1MEAN, AKMEAN, XKMEAN)
      CALL FEMEANWS_LOCAL(IPP, FL3,EMEANWS,FMEANWS(IPP),XLLWS)
      CALL FRCUTINDEX_LOCAL(IPP, FMEAN(IPP), FMEANWS(IPP), MIJ)
      IF(ISHALLO.EQ.1) THEN
        DO M=1,NFRE
          TEMP2(M) = FRM5(M)
        ENDDO
      ELSE
        DO M=1,NFRE
          AKM1 = 1./WK(M,IPP)
          AK2VGM1 = AKM1**2/CG(M,IPP)
          TEMP2(M) = AKM1*AK2VGM1
        ENDDO
      ENDIF
      GADIAG = 1./TEMP2(MIJ)
      DO M=1,MIJ
        FCONST(M) = 1.
        TEMP(M) = 0.
      ENDDO
      DO M=MIJ+1,NFRE
        FCONST(M) = 0.
        TEMP(M) = TEMP2(M)*GADIAG
      ENDDO
      DO K=1,NANG
        GADIAG = FL3(K,MIJ)
        DO M=1,NFRE
!AR: ICE            FLLOWEST = FLMINFR(JU),M)*SPRD(K)
!AR: ICE            FL3(IJ,K,M) = GADIAG*TEMP(M) &
!AR: ICE     &       + MAX(FL3(IJ,K,M),FLLOWEST)*FCONST(M)
            FL3(K,M) = GADIAG*TEMP(M) &
     &       + FL3(K,M)*FCONST(M)
!            WRITE(111113,'(2I10,10F20.10)')K,M,FL3(K,M),&
!     &                   TEMP(M),GADIAG,FCONST(M)
        ENDDO
      ENDDO

      IF (LOUTWAM) WRITE(111113,*) 'BEFORE WIND INPUT 2'
      IF (LOUTWAM) WRITE(111113,'(8F20.10)') SUM(FL3) , SUM(FL), THWNEW(IPP)
      IF (LOUTWAM) WRITE(111113,'(8F20.10)') USNEW(IPP), Z0NEW(IPP), ZIDLNEW(IPP)
      IF (LOUTWAM) WRITE(111113,'(8F20.10)') SUM(SL), SUM(XLLWS(:,:))

!     RECALC  

      IF(IPHYS.EQ.0) THEN
        CALL SINPUT_LOCAL (IPP, FL3, FL, THWNEW(IPP), USNEW(IPP), Z0NEW(IPP), &
     &             ROAIRN(IPP), WSTAR, SL, XLLWS, SSIN, DSSIN) 

!BUG ALARM  ... in the orignial code u have ther ZIDLNEW which is not used in sinput instead wstar is passed ...

      ELSE
        CALL SINPUT_ARD_LOCAL (IPP, FL3, FL, THWNEW(IPP), USNEW(IPP), Z0NEW(IPP), &
     &             ROAIRN(IPP), ZIDLNEW(IPP), SL, XLLWS, SSIN, DSSDS)
      ENDIF

      IF (LOUTWAM) WRITE(111113,*) 'AFTER SINPUT 2'
      IF (LOUTWAM) WRITE(111113,*) SUM(FL), SUM(SL)

      CALL STRESSO_LOCAL (IPP, FL3, THWNEW(IPP), USNEW(IPP), Z0NEW(IPP), &
     &              ROAIRN(IPP), TAUW(IPP), TAUWLF, PHIWA, &
     &              PHIAWDIAG, PHIAWUNR, SL, MIJ, &
     &              LCFLX)

      IF (LOUTWAM) WRITE(111113,*) 'AFTER STRESSO 2'
      IF (LOUTWAM) WRITE(111113,*) SUM(FL3), &

     &              THWNEW(IPP), USNEW(IPP), Z0NEW(IPP), &
     &              ROAIRN(IPP), TAUW(IPP), TAUWLF, PHIWA, &
     &              PHIAWDIAG, PHIAWUNR, SUM(SL), &
     &              MIJ

      CALL AIRSEA_LOCAL (IPP, U10NEW(IPP), TAUW(IPP), USNEW(IPP), Z0NEW(IPP), &
     & ILEV)

      IF (LOUTWAM) WRITE(111113,*) 'AFTER AIRSEA 3'
      IF (LOUTWAM) WRITE(111113,*) U10NEW(IPP), TAUW(IPP), &
      &                              USNEW(IPP), Z0NEW(IPP), ILEV

      IF(IPHYS.EQ.0) THEN
        CALL SDISSIP_LOCAL (IPP, FL3 ,FL, IG, SL, F1MEAN, XKMEAN, &
     &                PHIOC, TAUWD, MIJ, SSDS, DSSDS)
      ELSE
        CALL SDISS_ARDH_VEC_LOCAL (IPP, FL3 ,FL, SL, F1MEAN, XKMEAN, &
     &                PHIOC, TAUWD, MIJ, SSDS, DSSDS)
      ENDIF

      IF (LOUTWAM) WRITE(111110,'(A20,3F20.10)')  'END OF COMPUTATION', SUM(FL), SUM(SL), SUM(FL3)

      IF(LCFLX) THEN
        TAU       = ROAIRN(IPP)*USNEW(IPP)**2
        XN        = ROAIRN(IPP)*USNEW(IPP)**3

        PHIDIAG    = PHIAWDIAG+PHIAWUNR
        PHIEPS = (PHIOC-PHIDIAG)/XN 
        PHIAW  = (PHIWA+PHIAWUNR)/XN
        TAUOC  = (TAU-TAUWLF-TAUWD)/TAU
      ENDIF

        USOLD(IPP,1) = USNEW(IPP)
        Z0OLD(IPP,1) = Z0NEW(IPP)
        ROAIRO(IPP,1) = ROAIRN(IPP)
        ZIDLOLD(IPP,1) = ZIDLNEW(IPP)
        UFRIC(IPP) = USNEW(IPP)
        Z0(IPP)    = Z0NEW(IPP)
        CD(IPP)   = (USNEW(IPP)/U10NEW(IPP))**2
        ALPHA_CH(IPP) = G*Z0NEW(IPP)/USNEW(IPP)**2

      END SUBROUTINE IMPLSCH_LOCAL

    SUBROUTINE WAM_PRE (IPP, FL3, FL, SL, SSDSO, DSSDSO, SSNL4O, DSSNL4O, SSINO, DSSINO)

       USE DATAPOOL, ONLY : MNP, FR, WETAIL, FRTAIL, WP1TAIL, ISHALLO, FRINTF, COFRM4, CG, WK, &
     &                      DFIM, DFIMOFR, DFFR, DFFR2, WK, RKIND, EMEAN, FMEAN, TH, RKIND, DELU, &
     &                      JUMAX, DT4S, FRM5, IPHYS, LOUTWAM, CD, UFRIC, ALPHA_CH, Z0, ITEST, LCFLX,&
     &                      THWOLD, THWNEW, Z0OLD, Z0NEW, ROAIRO, ROAIRN, ZIDLOLD, ZIDLNEW, U10NEW, USNEW, &
     &                      U10OLD, FMEANWS, USOLD, TAUW, &
     &                      DELTH => DDIR, &
     &                      G => G9, &
     &                      ZPI => PI2, &
     &                      EPSMIN => SMALL, &
     &                      NANG => MDC, &
     &                      NFRE => MSC, &
     &                      INDEP => DEP, &
     &                      ROWATER => RHOW, &
     &                      RHOAIR => RHOA

      INTEGER, INTENT(IN) :: IPP
      REAL(rkind),DIMENSION(NANG,NFRE),INTENT(IN)  :: FL3
      REAL(rkind),DIMENSION(NANG,NFRE),INTENT(OUT) :: FL,SL 
      REAL(rkind),DIMENSION(NFRE,NANG),INTENT(OUT) :: SSDSO,DSSDSO,SSNL4O,DSSNL4O,SSINO,DSSINO

      INTEGER :: K,L,M,IG,ILEV
      INTEGER :: MIJ
      INTEGER :: JU

      REAL(rkind) :: GTEMP1, GTEMP2, FLHAB, XJ, DELT, DELT5, XIMP, AKM1
      REAL(rkind) :: AK2VGM1, XN, PHIDIAG, TAU
      REAL(rkind) :: EMEANWS, USFM, GADIAG
      REAL(rkind) :: F1MEAN, AKMEAN, XKMEAN
      REAL(rkind) :: PHIEPS, TAUOC, PHIAW, WSTAR,FPM,WIND10,WINDTH
      REAL(rkind) :: TAUWLF,TAUWD,PHIAWDIAG,PHIAWUNR,PHIOC,PHIWA

      INTEGER    , DIMENSION(NFRE)     :: FCONST
      REAL(rkind), DIMENSION(NANG)     :: SPRD
      REAL(rkind), DIMENSION(NFRE)     :: TEMP, TEMP2, DELFL
      REAL(rkind),DIMENSION(NANG,NFRE) :: SSDS,DSSDS,SSBF,DSSBF,SSNL4,DSSNL4,SSIN,DSSIN,CIWAB,XLLWS

      SL = 0.d0
      FL = 0.d0
      CALL FKMEAN_LOCAL(IPP, FL3, EMEAN(IPP), FMEAN(IPP),F1MEAN, AKMEAN, XKMEAN)
      SPRD=MAX(0.d0,COS(TH-THWNEW(IPP)))**2
      XJ=U10NEW(IPP)/DELU
      JU=MIN(JUMAX, MAX(NINT(XJ),1))
      ILEV=1
      CALL AIRSEA_LOCAL (IPP, U10NEW(IPP), TAUW(IPP), USNEW(IPP), Z0NEW(IPP),ILEV)
      IF(IPHYS.EQ.0) THEN
        CALL SINPUT_LOCAL (IPP, FL3, FL, THWNEW(IPP), USNEW(IPP), Z0NEW(IPP), ROAIRN(IPP), ZIDLNEW(IPP), SL, XLLWS, SSIN, DSSIN)
      ELSE
        CALL SINPUT_ARD_LOCAL (IPP, FL3, FL, THWNEW(IPP), USNEW(IPP), Z0NEW(IPP), ROAIRN(IPP), ZIDLNEW(IPP), SL, XLLWS, SSIN, DSSIN)
      ENDIF
      CALL FEMEANWS_LOCAL(IPP,FL3,EMEANWS,FMEANWS(IPP),XLLWS)
      CALL FRCUTINDEX_LOCAL(IPP, FMEAN(IPP), FMEANWS(IPP), MIJ)
      CALL STRESSO_LOCAL (IPP, FL3, THWNEW(IPP), USNEW(IPP), Z0NEW(IPP), ROAIRN(IPP), TAUW(IPP), TAUWLF, PHIWA, PHIAWDIAG, PHIAWUNR, SL, MIJ, LCFLX)
      CALL AIRSEA_LOCAL (IPP, U10NEW(IPP), TAUW(IPP), USNEW(IPP), Z0NEW(IPP), ILEV)
      CALL SNONLIN_LOCAL (IPP, FL3, FL, IG, SL, AKMEAN, SSNL4, DSSNL4)
      IF(IPHYS.EQ.0) THEN
        CALL SDISSIP_LOCAL (IPP, FL3 ,FL, IG, SL, F1MEAN, XKMEAN, PHIOC, TAUWD, MIJ, SSDS, DSSDS)
      ELSE
        CALL SDISS_ARDH_VEC_LOCAL (IPP, FL3 ,FL, SL, F1MEAN, XKMEAN,PHIOC, TAUWD, MIJ, SSDS, DSSDS)
      ENDIF
      DO K = 1, NANG
        DO M = 1, NFRE
          SSDSO(M,K) = SSDS(K,M)
          DSSDSO(M,K) = DSSDS(K,M)
          SSNL4O(M,K) = SSNL4(K,M)
          DSSNL4O(M,K) = DSSNL4(K,M)
          SSINO(M,K) = SSIN(K,M)
          DSSINO(M,K) = DSSIN(K,M)
        ENDDO
      ENDDO
!SHALLOW
      !IF(ISHALLO.NE.1) CALL SBOTTOM (FL3, FL, IJS, IJL, IG, SL, SSBF, DSSBF)
!SHALLOW
      END SUBROUTINE WAM_PRE 

      
    SUBROUTINE WAM_POST (IPP, FL3)

       USE DATAPOOL, ONLY : MNP, FR, WETAIL, FRTAIL, WP1TAIL, ISHALLO, FRINTF, COFRM4, CG, WK, &
     &                      DFIM, DFIMOFR, DFFR, DFFR2, WK, RKIND, EMEAN, FMEAN, TH, RKIND, DELU, &
     &                      JUMAX, DT4S, FRM5, IPHYS, LOUTWAM, CD, UFRIC, ALPHA_CH, Z0, ITEST, LCFLX,&
     &                      THWOLD, THWNEW, Z0OLD, Z0NEW, ROAIRO, ROAIRN, ZIDLOLD, ZIDLNEW, U10NEW, USNEW, &
     &                      U10OLD, FMEANWS, USOLD, TAUW, &
     &                      DELTH => DDIR, &
     &                      G => G9, &
     &                      ZPI => PI2, &
     &                      EPSMIN => SMALL, &
     &                      NANG => MDC, &
     &                      NFRE => MSC, &
     &                      INDEP => DEP, &
     &                      ROWATER => RHOW, &
     &                      RHOAIR => RHOA

      INTEGER, INTENT(IN) :: IPP

      INTEGER :: K,L,M,IG,ILEV,IDELT,IU06
      INTEGER :: MIJ
      INTEGER :: JU

      REAL(rkind) :: GTEMP1, GTEMP2, FLHAB, XJ, DELT, DELT5, XIMP, AKM1
      REAL(rkind) :: AK2VGM1, XN, PHIDIAG, TAU
      REAL(rkind) :: EMEANWS, USFM, GADIAG
      REAL(rkind) :: F1MEAN, AKMEAN, XKMEAN
      REAL(rkind) :: PHIEPS, TAUOC, PHIAW, WSTAR
      REAL(rkind) :: TAUWLF,TAUWD,PHIAWDIAG,PHIAWUNR,PHIOC,PHIWA

      INTEGER    , DIMENSION(NFRE)     :: FCONST
      REAL(rkind), DIMENSION(NANG)     :: SPRD
      REAL(rkind), DIMENSION(NFRE)     :: TEMP, TEMP2, DELFL
      REAL(rkind),DIMENSION(NANG,NFRE) :: SSDS,DSSDS,SSBF,DSSBF,SSNL4,DSSNL4,SSIN,DSSIN,FL,FL3,SL,CIWAB,XLLWS

      IDELT = INT(DT4S)
      ILEV  = 1
      SL = 0.d0
      FL = 0.d0

      CALL FKMEAN_LOCAL(IPP, FL3, EMEAN(IPP), FMEAN(IPP), F1MEAN, AKMEAN, XKMEAN)
      CALL FEMEANWS_LOCAL(IPP, FL3,EMEANWS,FMEANWS(IPP),XLLWS)
      CALL FRCUTINDEX_LOCAL(IPP, FMEAN(IPP), FMEANWS(IPP), MIJ)

      IF(ISHALLO.EQ.1) THEN
       TEMP2 = FRM5
      ELSE
        DO M=1,NFRE
          AKM1 = 1./WK(M,IPP)
          AK2VGM1 = AKM1**2/CG(M,IPP)
          TEMP2(M) = AKM1*AK2VGM1
        ENDDO
      ENDIF
      GADIAG = 1./TEMP2(MIJ)

      DO M=1,MIJ
        FCONST(M) = 1.
        TEMP(M) = 0.
      ENDDO
      DO M=MIJ+1,NFRE
        FCONST(M) = 0.
        TEMP(M) = TEMP2(M)*GADIAG
      ENDDO
      DO K=1,NANG
        GADIAG = FL3(K,MIJ)
        DO M=1,NFRE
!AR: ICE            FLLOWEST = FLMINFR(JU),M)*SPRD(K)
!AR: ICE            FL3(IJ,K,M) = GADIAG*TEMP(M) &
!AR: ICE     &       + MAX(FL3(IJ,K,M),FLLOWEST)*FCONST(M)
            FL3(K,M) = GADIAG*TEMP(M) + FL3(K,M)*FCONST(M)
        ENDDO
      ENDDO
 
      IF(IPHYS.EQ.0) THEN
        CALL SINPUT_LOCAL (IPP, FL3, FL, THWNEW(IPP), USNEW(IPP), Z0NEW(IPP), ROAIRN(IPP), WSTAR, SL, XLLWS, SSIN, DSSIN)
!BUG ALARM  ... in the orignial code u have ther ZIDLNEW which is not used in sinput instead wstar is passed ...
      ELSE
        CALL SINPUT_ARD_LOCAL (IPP, FL3, FL, THWNEW(IPP), USNEW(IPP), Z0NEW(IPP), ROAIRN(IPP), ZIDLNEW(IPP), SL, XLLWS, SSIN, DSSDS)
      ENDIF

      CALL STRESSO_LOCAL (IPP, FL3, THWNEW(IPP), USNEW(IPP), Z0NEW(IPP), ROAIRN(IPP), TAUW(IPP), TAUWLF, PHIWA,PHIAWDIAG, PHIAWUNR, SL, MIJ,LCFLX)
      CALL AIRSEA_LOCAL (IPP, U10NEW(IPP), TAUW(IPP), USNEW(IPP), Z0NEW(IPP),ILEV)

      IF(IPHYS.EQ.0) THEN
        CALL SDISSIP_LOCAL (IPP, FL3 ,FL, IG, SL, F1MEAN, XKMEAN, PHIOC, TAUWD, MIJ, SSDS, DSSDS)
      ELSE
        CALL SDISS_ARDH_VEC_LOCAL (IPP, FL3 ,FL, SL, F1MEAN, XKMEAN,PHIOC, TAUWD, MIJ, SSDS, DSSDS)
      ENDIF

      TAU       = ROAIRN(IPP)*USNEW(IPP)**2
      XN        = ROAIRN(IPP)*USNEW(IPP)**3
      PHIDIAG    = PHIAWDIAG+PHIAWUNR
      PHIEPS = (PHIOC-PHIDIAG)/XN 
      PHIAW  = (PHIWA+PHIAWUNR)/XN
      TAUOC  = (TAU-TAUWLF-TAUWD)/TAU
      USOLD(IPP,1) = USNEW(IPP)
      Z0OLD(IPP,1) = Z0NEW(IPP)
      ROAIRO(IPP,1) = ROAIRN(IPP)
      ZIDLOLD(IPP,1) = ZIDLNEW(IPP)
      UFRIC(IPP) = USNEW(IPP)
      Z0(IPP)    = Z0NEW(IPP)
      CD(IPP)   = (USNEW(IPP)/U10NEW(IPP))**2
      ALPHA_CH(IPP) = G*Z0NEW(IPP)/USNEW(IPP)**2

      END SUBROUTINE WAM_POST 
