      SUBROUTINE WAM_PRE (IPP, FL3, FL, SL, SSDSO, DSSDSO, SSNL4O, DSSNL4O, SSINO, DSSINO)

      USE DATAPOOL, ONLY : MNP, FR, WETAIL, FRTAIL, WP1TAIL, ISHALLO, FRINTF, COFRM4, CG, WK, &
     &                      DFIM, DFIMOFR, DFFR, DFFR2, WK, RKIND, EMEAN, FMEAN, TH, RKIND, DELU, &
     &                      JUMAX, DT4S, FRM5, IPHYS, LOUTWAM, CD, UFRIC, ALPHA_CH, Z0, ITEST, LCFLX,&
     &                      THWOLD, THWNEW, Z0OLD, Z0NEW, ROAIRO, ROAIRN, ZIDLOLD, ZIDLNEW, U10NEW, USNEW, &
     &                      U10OLD, FMEANWS, USOLD, TAUW, &
     &                      DELTH => DDIR, &
     &                      G => G9, &
     &                      ZPI => PI2, &
     &                      EPSMIN => SMALL, &
     &                      NANG => MDC, &
     &                      NFRE => MSC, &
     &                      INDEP => DEP, &
     &                      ROWATER => RHOW, &
     &                      RHOAIR => RHOA
      IMPLICIT NONE
      INTEGER, INTENT(IN) :: IPP
      REAL(rkind),DIMENSION(NANG,NFRE),INTENT(IN)  :: FL3
      REAL(rkind),DIMENSION(NANG,NFRE),INTENT(OUT) :: FL,SL 
      REAL(rkind),DIMENSION(NFRE,NANG),INTENT(OUT) :: SSDSO,DSSDSO,SSNL4O,DSSNL4O,SSINO,DSSINO

      INTEGER :: K,L,M,ILEV
      INTEGER :: MIJ
      INTEGER :: JU

      REAL(rkind) :: GTEMP1, GTEMP2, FLHAB, XJ, DELT, DELT5, XIMP, AKM1
      REAL(rkind) :: AK2VGM1, XN, PHIDIAG, TAU
      REAL(rkind) :: EMEANWS, USFM, GADIAG
      REAL(rkind) :: F1MEAN, AKMEAN, XKMEAN
      REAL(rkind) :: PHIEPS, TAUOC, PHIAW, WSTAR,FPM,WIND10,WINDTH
      REAL(rkind) :: TAUWLF,TAUWD,PHIAWDIAG,PHIAWUNR,PHIOC,PHIWA

      INTEGER    , DIMENSION(NFRE)     :: FCONST
      REAL(rkind), DIMENSION(NANG)     :: SPRD
      REAL(rkind), DIMENSION(NFRE)     :: TEMP, TEMP2, DELFL
      REAL(rkind),DIMENSION(NANG,NFRE) :: SSDS,DSSDS,SSBF,DSSBF,SSNL4,DSSNL4,SSIN,DSSIN,CIWAB,XLLWS

      CALL FKMEAN_LOCAL(IPP, FL3, EMEAN(IPP), FMEAN(IPP),F1MEAN, AKMEAN, XKMEAN)
      SPRD=MAX(0.d0,COS(TH-THWNEW(IPP)))**2
      XJ=U10NEW(IPP)/DELU
      JU=MIN(JUMAX, MAX(NINT(XJ),1))
      ILEV=1
      CALL AIRSEA_LOCAL (IPP, U10NEW(IPP), TAUW(IPP), USNEW(IPP), Z0NEW(IPP),ILEV)
      IF(IPHYS.EQ.0) THEN
        CALL SINPUT_LOCAL (IPP, FL3, FL, THWNEW(IPP), USNEW(IPP), Z0NEW(IPP), ROAIRN(IPP), ZIDLNEW(IPP), SL, XLLWS, SSIN, DSSIN)
      ELSE
        CALL SINPUT_ARD_LOCAL (IPP, FL3, FL, THWNEW(IPP), USNEW(IPP), Z0NEW(IPP), ROAIRN(IPP), ZIDLNEW(IPP), SL, XLLWS, SSIN, DSSIN)
      ENDIF
      CALL FEMEANWS_LOCAL(IPP,FL3,EMEANWS,FMEANWS(IPP),XLLWS)
      CALL FRCUTINDEX_LOCAL(IPP, FMEAN(IPP), FMEANWS(IPP), MIJ)
      CALL STRESSO_LOCAL (IPP, FL3, THWNEW(IPP), USNEW(IPP), Z0NEW(IPP), ROAIRN(IPP), TAUW(IPP), TAUWLF, PHIWA, PHIAWDIAG, PHIAWUNR, SL, MIJ, LCFLX)
      CALL AIRSEA_LOCAL (IPP, U10NEW(IPP), TAUW(IPP), USNEW(IPP), Z0NEW(IPP), ILEV)
      CALL SNONLIN_LOCAL (IPP, FL3, FL, SL, AKMEAN, SSNL4, DSSNL4)
      IF(IPHYS.EQ.0) THEN
        CALL SDISSIP_LOCAL (IPP, FL3 ,FL, SL, F1MEAN, XKMEAN, PHIOC, TAUWD, MIJ, SSDS, DSSDS)
      ELSE
        CALL SDISS_ARDH_VEC_LOCAL (IPP, FL3 ,FL, SL, F1MEAN, XKMEAN,PHIOC, TAUWD, MIJ, SSDS, DSSDS)
      ENDIF
      DO K = 1, NANG
        DO M = 1, NFRE
          SSDSO(M,K) = SSDS(K,M)
          DSSDSO(M,K) = DSSDS(K,M)
          SSNL4O(M,K) = SSNL4(K,M)
          DSSNL4O(M,K) = DSSNL4(K,M)
          SSINO(M,K) = SSIN(K,M)
          DSSINO(M,K) = DSSIN(K,M)
        ENDDO
      ENDDO
      END SUBROUTINE WAM_PRE 

      
      SUBROUTINE WAM_POST (IPP, FL3)
       USE DATAPOOL, ONLY : MNP, FR, WETAIL, FRTAIL, WP1TAIL, ISHALLO, FRINTF, COFRM4, CG, WK, &
     &                      DFIM, DFIMOFR, DFFR, DFFR2, WK, RKIND, EMEAN, FMEAN, TH, RKIND, DELU, &
     &                      JUMAX, DT4S, FRM5, IPHYS, LOUTWAM, CD, UFRIC, ALPHA_CH, Z0, ITEST, LCFLX,&
     &                      THWOLD, THWNEW, Z0OLD, Z0NEW, ROAIRO, ROAIRN, ZIDLOLD, ZIDLNEW, U10NEW, USNEW, &
     &                      U10OLD, FMEANWS, USOLD, TAUW, &
     &                      DELTH => DDIR, &
     &                      G => G9, &
     &                      ZPI => PI2, &
     &                      EPSMIN => SMALL, &
     &                      NANG => MDC, &
     &                      NFRE => MSC, &
     &                      INDEP => DEP, &
     &                      ROWATER => RHOW, &
     &                      RHOAIR => RHOA
      IMPLICIT NONE
      INTEGER, INTENT(IN) :: IPP

      INTEGER :: K,L,M,ILEV,IDELT,IU06
      INTEGER :: MIJ
      INTEGER :: JU

      REAL(rkind) :: GTEMP1, GTEMP2, FLHAB, XJ, DELT, DELT5, XIMP, AKM1
      REAL(rkind) :: AK2VGM1, XN, PHIDIAG, TAU
      REAL(rkind) :: EMEANWS, USFM, GADIAG
      REAL(rkind) :: F1MEAN, AKMEAN, XKMEAN
      REAL(rkind) :: PHIEPS, TAUOC, PHIAW, WSTAR
      REAL(rkind) :: TAUWLF,TAUWD,PHIAWDIAG,PHIAWUNR,PHIOC,PHIWA

      INTEGER    , DIMENSION(NFRE)     :: FCONST
      REAL(rkind), DIMENSION(NANG)     :: SPRD
      REAL(rkind), DIMENSION(NFRE)     :: TEMP, TEMP2, DELFL
      REAL(rkind),DIMENSION(NANG,NFRE) :: SSDS,DSSDS,SSIN,DSSIN,FL,FL3,SL,XLLWS

      IDELT = INT(DT4S)
      ILEV  = 1
      SL = 0.d0
      FL = 0.d0

      CALL FKMEAN_LOCAL(IPP, FL3, EMEAN(IPP), FMEAN(IPP), F1MEAN, AKMEAN, XKMEAN)
      CALL FEMEANWS_LOCAL(IPP, FL3,EMEANWS,FMEANWS(IPP),XLLWS)
      CALL FRCUTINDEX_LOCAL(IPP, FMEAN(IPP), FMEANWS(IPP), MIJ)

      IF(ISHALLO.EQ.1) THEN
       TEMP2 = FRM5
      ELSE
        DO M=1,NFRE
          AKM1 = 1./WK(M,IPP)
          AK2VGM1 = AKM1**2/CG(M,IPP)
          TEMP2(M) = AKM1*AK2VGM1
        ENDDO
      ENDIF
      GADIAG = 1./TEMP2(MIJ)

      DO M=1,MIJ
        FCONST(M) = 1.
        TEMP(M) = 0.
      ENDDO
      DO M=MIJ+1,NFRE
        FCONST(M) = 0.
        TEMP(M) = TEMP2(M)*GADIAG
      ENDDO
      DO K=1,NANG
        GADIAG = FL3(K,MIJ)
        DO M=1,NFRE
!AR: ICE            FLLOWEST = FLMINFR(JU),M)*SPRD(K)
!AR: ICE            FL3(IJ,K,M) = GADIAG*TEMP(M) &
!AR: ICE     &       + MAX(FL3(IJ,K,M),FLLOWEST)*FCONST(M)
            FL3(K,M) = GADIAG*TEMP(M) + FL3(K,M)*FCONST(M)
        ENDDO
      ENDDO
 
      IF(IPHYS.EQ.0) THEN
        CALL SINPUT_LOCAL (IPP, FL3, FL, THWNEW(IPP), USNEW(IPP), Z0NEW(IPP), ROAIRN(IPP), WSTAR, SL, XLLWS, SSIN, DSSIN)
!BUG ALARM  ... in the orignial code u have ther ZIDLNEW which is not used in sinput instead wstar is passed ...
      ELSE
        CALL SINPUT_ARD_LOCAL (IPP, FL3, FL, THWNEW(IPP), USNEW(IPP), Z0NEW(IPP), ROAIRN(IPP), ZIDLNEW(IPP), SL, XLLWS, SSIN, DSSDS)
      ENDIF

      CALL STRESSO_LOCAL (IPP, FL3, THWNEW(IPP), USNEW(IPP), Z0NEW(IPP), ROAIRN(IPP), TAUW(IPP), TAUWLF, PHIWA,PHIAWDIAG, PHIAWUNR, SL, MIJ,LCFLX)
      CALL AIRSEA_LOCAL (IPP, U10NEW(IPP), TAUW(IPP), USNEW(IPP), Z0NEW(IPP),ILEV)

      IF(IPHYS.EQ.0) THEN
        CALL SDISSIP_LOCAL (IPP, FL3 ,FL, SL, F1MEAN, XKMEAN, PHIOC, TAUWD, MIJ, SSDS, DSSDS)
      ELSE
        CALL SDISS_ARDH_VEC_LOCAL (IPP, FL3 ,FL, SL, F1MEAN, XKMEAN,PHIOC, TAUWD, MIJ, SSDS, DSSDS)
      ENDIF

      TAU       = ROAIRN(IPP)*USNEW(IPP)**2
      XN        = ROAIRN(IPP)*USNEW(IPP)**3
      PHIDIAG    = PHIAWDIAG+PHIAWUNR
      PHIEPS = (PHIOC-PHIDIAG)/XN 
      PHIAW  = (PHIWA+PHIAWUNR)/XN
      TAUOC  = (TAU-TAUWLF-TAUWD)/TAU
      USOLD(IPP,1) = USNEW(IPP)
      Z0OLD(IPP,1) = Z0NEW(IPP)
      ROAIRO(IPP,1) = ROAIRN(IPP)
      ZIDLOLD(IPP,1) = ZIDLNEW(IPP)
      UFRIC(IPP) = USNEW(IPP)
      Z0(IPP)    = Z0NEW(IPP)
      CD(IPP)   = (USNEW(IPP)/U10NEW(IPP))**2
      ALPHA_CH(IPP) = G*Z0NEW(IPP)/USNEW(IPP)**2

      END SUBROUTINE WAM_POST 
