        !COMPILER-GENERATED INTERFACE MODULE: Sun May 11 20:52:45 2014
        MODULE CT2MJD__genmod
          INTERFACE 
            SUBROUTINE CT2MJD(STIME,XMJD)
              CHARACTER(LEN=15), INTENT(IN) :: STIME
              REAL(KIND=8), INTENT(INOUT) :: XMJD
            END SUBROUTINE CT2MJD
          END INTERFACE 
        END MODULE CT2MJD__genmod
