        !COMPILER-GENERATED INTERFACE MODULE: Sun May 11 20:52:45 2014
        MODULE MEAN_PARAMETER_LOC__genmod
          INTERFACE 
            SUBROUTINE MEAN_PARAMETER_LOC(ACLOC,ACLOC2D,CURTXYLOC,DEPLOC&
     &,WKLOC,ISMAX,HS,TM01,TM02,KLM,WLM)
              USE STAT_POOL
              REAL(KIND=4), INTENT(IN) :: ACLOC(MSC,MDC)
              REAL(KIND=4), INTENT(IN) :: ACLOC2D(MSC,MDC)
              REAL(KIND=4), INTENT(IN) :: CURTXYLOC(2)
              REAL(KIND=4), INTENT(IN) :: DEPLOC
              REAL(KIND=4), INTENT(IN) :: WKLOC(MSC)
              INTEGER(KIND=4), INTENT(IN) :: ISMAX
              REAL(KIND=8), INTENT(OUT) :: HS
              REAL(KIND=8), INTENT(OUT) :: TM01
              REAL(KIND=8), INTENT(OUT) :: TM02
              REAL(KIND=8), INTENT(OUT) :: KLM
              REAL(KIND=8), INTENT(OUT) :: WLM
            END SUBROUTINE MEAN_PARAMETER_LOC
          END INTERFACE 
        END MODULE MEAN_PARAMETER_LOC__genmod
