        !COMPILER-GENERATED INTERFACE MODULE: Sun May 11 20:52:45 2014
        MODULE MJD2CT__genmod
          INTERFACE 
            SUBROUTINE MJD2CT(XMJD,STIME)
              REAL(KIND=8), INTENT(IN) :: XMJD
              CHARACTER(LEN=15), INTENT(INOUT) :: STIME
            END SUBROUTINE MJD2CT
          END INTERFACE 
        END MODULE MJD2CT__genmod
