        !COMPILER-GENERATED INTERFACE MODULE: Sun May 11 20:52:45 2014
        MODULE TEST_FILE_EXIST_DIE__genmod
          INTERFACE 
            SUBROUTINE TEST_FILE_EXIST_DIE(STRING1,STRING2)
              CHARACTER(*) :: STRING1
              CHARACTER(*) :: STRING2
            END SUBROUTINE TEST_FILE_EXIST_DIE
          END INTERFACE 
        END MODULE TEST_FILE_EXIST_DIE__genmod
