

default:
	(cd Lib ; $(MAKE) ) 
#	(cd ParMETISLib ; $(MAKE) ) 
#	(cd Programs ; $(MAKE) ) 

clean:
	(cd Lib ; $(MAKE) realclean )
#	(cd ParMETISLib ; $(MAKE) realclean )
#	(cd Programs ; $(MAKE) realclean )


